import { Box, Container, Flex, Heading, Link, Text } from '@chakra-ui/react';
import Generator from '../components/Generator';

function HomePage() {
    return (
        <>
            <Box py={10}>
                <Container maxW="960px">
                    <Generator />
                </Container>
            </Box>
            <Box
                as="section"
                bg="gray.100"
                py={10}
            >
                <Container maxW="960">
                    <Flex
                        flexDirection="column"
                        sx={{ gap: 5 }}
                    >
                        <Heading>FAQ</Heading>
                        <Text>
                            Unified Payments Interface (UPI is an instant, peer-to-peer payment system introduced by National Payments Corporation of India (NPCI).
                            Transactions done through UPI are settled in real-time and no transaction fees is charged by the banks.
                        </Text>
                        <Heading fontSize="large">Privacy</Heading>
                        <Text>
                            Your data including merchant name, VPA or anything entered in this UPI QR code generator is not stored with us.
                            The service works completely in browser and nothing is sent to our servers.
                        </Text>
                        <Text>
                            This website is also open-source (see <Link href="https://github.com/syncloudsoftech/upiqr" target="_blank">https://github.com/syncloudsoftech/upiqr</Link>) and code can be freely reviewed for extended concerns.
                        </Text>
                        <Heading fontSize="large">Disclaimer</Heading>
                        <Text>
                            Names and logos shown are property of their respective owners.
                            This website is designed to help merchants quickly generate UPI QR codes with custom amount and notes.
                            This website or our company is not related to any bank, BHIM, NPCI or any other financial institution.
                        </Text>
                        <Text>
                            Users are advised to always checked the downloaded QR code for errors.
                            Our company does not take responsibility for any direct or indirect loss due to errors in the QR codes generated by this website.
                        </Text>
                    </Flex>
                </Container>
            </Box>
            <Box
                as="section"
                bg="gray.200"
                p={10}
            >
                <Text textAlign="center"><Link href="https://syncloudsoft.com/" target="_blank">Syncloud Softech</Link> (P) Ltd. &copy; 2022</Text>
            </Box>
        </>
    )
}

export default HomePage;
